### ISSUE TITLE
Add email notification to all users when a new application version becomes active in the portfolio

### ISSUE THREAD

**Issue by llopat** [nmaas-platform/nmaas-platform#4]
This functionality should be triggered conditionally, meaning that the user / admin who changes the application version state to ACTIVE is provided with a checkbox and can choose whether to send out the notification email or not.
Model needs to be extended to include the new boolean flag.
New email template with appropriate content has to be prepared.

**Comment by llopat** [comment]
@pgiertych please verify how email notifications are being sent out from the platform and how those can be triggered upon new application addition to portfolio

**Comment by llopat** [comment]
Proposed content of the respective email:


    {
      "language": "en",
      "subject": "NMaaS: New application version available in the portfolio",
      "template": {
        "HEADER": "Dear ${username},",
        "CONTENT": "${appName} application in version ${appVersion} was added to the portfolio and is now available for deployment.",
        "SENDER": "Best regards,<br />NMaaS Team",
        "NOREPLY": "This is an automatically generated message, please do not reply.",
        "SENDER_POLICY": ""
      }
    },

**Comment by llopat** [comment]
It seems that proper template input parameters are not being passed when sending the email.


```
2023-02-21 07:12:38,360 [Executor-150179] ERROR                            freemarker.runtime:  60 - Error executing FreeMarker template
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> appName  [in template "CONTENT" at line 1, column 3]


FTL stack trace ("~" means nesting-related):
        - Failed at: ${appName}  [in template "CONTENT" at line 1, column 1]
       at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) ~[freemarker-2.3.31.jar!/:2.3.31]
        at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481) ~[freemarker-2.3.31.jar!/:2.3.31]
        at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401) ~[freemarker-2.3.31.jar!/:2.3.31]
```
